[package]
name = "git-trace"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Philippe Soubrier <philippe.soubrier@gmail.com>"]
license = "MIT"
description = "Surface Git reflog metadata in documents."
